### ISSUE TITLE
stuck on the "Language Chooser" 

### ISSUE THREAD

**Issue by constin** [kholia/OSX-KVM#26]
I'm stuck on stuck on the "Language Chooser" menu bar (with no option to launch Disk Utility) and waiting don't help. i tried 10 times with waiting for 5 minutes with and without pressing key and push.

**Comment by matspi** [comment]
Why don't you choose a language?

**Comment by constin** [comment]
I did. First screen is choose language , but without "Language Chooser" in menu.  Second screen it to choose disk with  "Language Chooser" in menu. So i could not launch disk utility.   I tried to wait 1-5 min but nothing happens. May be it possible to launch disk utility from hotkey or prepare  HSM disk before mac os installation.

**Comment by constin** [comment]
<img width="1020" alt="screen shot 2016-10-28 at 17 03 18" src="https://cloud.githubusercontent.com/assets/5740321/19811146/7affe68e-9d30-11e6-9755-cb69a9955184.png">

**Comment by kholia** [comment]
The solution (which I have used successfully) is written down in the https://github.com/kholia/OSX-KVM/blob/master/README.md file.

Please read it carefully.

**Comment by constin** [comment]
-  While booting from the macOS Sierra ISO installer, you might get stuck on the "Language Chooser" menu bar (with no option to launch Disk Utility). The solution is to wait for a few seconds on the "Language Chooser" screen itself without pressing the forward button.

I wait , but nothing happens.
I run KVM from Proxmox with your prepare scripts.
http://www.nicksherlock.com/2016/10/installing-macos-sierra-on-proxmox-4-3-qemu-2-6-1/

**Comment by kholia** [comment]
See https://discussions.apple.com/thread/7676399 discussion thread (this is where I got my solution from).

"My issue finally went away on its own. I accessed the recovery mode multiple times since last evening, when I first downloaded and installed macOS Sierra. Each time the Language Chooser remained the only option in the menu bar - frustrating! Then, just about an hour ago, I tried yet again. The ONLY think I did differently upon reaching the menu screen with the 4 actionable choices, I paused for a few seconds longer until I was sure everything was loaded and then moved my cursor to the top of the screen where, PRESTO, the old familiar menu bar appeared, with Utilities drop-down folder. I was able to access the Terminal and all was well!"

If this doesn't work for you, I have no further tips.

**Comment by Maxqia** [comment]
For me, I used [this](https://support.apple.com/en-us/HT201372), which creates a utility usb drive instead of a install-only one, which circumvented the issue for me. (I imported it using -hda \*insert block device here\*)

**Comment by constin** [comment]
I prepaid disk by Capitan installer before install Sierra.

**Comment by kholia** [comment]
I am glad that the problem is solved.

**Comment by IceHawk66** [comment]
Stuck there as well...I waited a few minutes without moving the mouse, but I still cant access the disk utility. Any ideas?

**Comment by constin** [comment]
try to format disk  by EI Capitan (or linux) before Sierra installation. And will don't need this step.

**Comment by IceHawk66** [comment]
How did you do that?

**Comment by constin** [comment]
Make all steps with IE Capitan distr from start to Disk Utility step. Prepare  disk by EI Capitan. Stop VM. Change ISO in config file to Sierra ISO. Don't forget to change CPU type.  Start VM with Sierra . Ur disk will be already done for install. Choose your disk as install disk. Installation will start.

**Comment by IceHawk66** [comment]
Ah i got your point now. This error is exists only in Sierra, not in El Capitan. I'll try it, thanks.

**Comment by Ethergeist** [comment]
Just because this is easier than getting El Capitan, one can use the -x flag at the boot prompt to go into safe mode, and the installer works as intended.

**Comment by kholia** [comment]
I have received a report saying,

Just because this is easier than getting El Capitan, one can use the -x flag at the boot prompt to go into safe mode, and the installer works as intended.

**Comment by pdxjohnny** [comment]
@elementh I'm sitting here mashing random keys and it popped a shell. Was so stoked. 12/10 would mash keyboard again.

**Comment by alinelena** [comment]
for me super+t did the trick, quite reliable in the language screen

**Comment by mtl** [comment]
Had to use `diskutil eraseDisk JHFS+ NameOfTheHDD disk1`, for disk0 was the Install OSX volume.

**Comment by raynix** [comment]
Here's how to use Linux tools to prepare the disk partition. It's a success at the end.

http://raynix.info/archives/3368

**Comment by kholia** [comment]
I ran into this problem today on 10.12.2. I used Ctrl+F2 and arrow keys to navigate the "macOS Installer" menu bar, and to launch "Disk Utility".

**Comment by kfirufk** [comment]
welp.. today I tried re-installing macos using your wonderful project with a bit of parameters modifications, and this time the top menu bar works properly. in general I just set the vga and audio devices. 

```
qemu-system-x86_64 -enable-kvm -m 8192 -cpu Penryn,kvm=off,vendor=GenuineIntel \
	  -machine pc-q35-2.4 \
	  -smp 4,cores=2 \
	  -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" \
	  -kernel ./enoch_rev2839_boot \
	  -smbios type=2 \
	  -device ide-drive,bus=ide.2,drive=MacHDD \
	  -drive id=MacHDD,if=none,file=./mac_hdd.qcow2 \
	  -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
	  -daemonize \
	   -usb -device usb-kbd \
	   -device usb-mouse  \
	   -soundhw hda \
	   -vga vmware \
	   -device ide-drive,bus=ide.0,drive=MacDVD \
	   -drive id=MacDVD,if=none,snapshot=on,file=./'Install_macOS_Sierra_10.12.3.iso' \
	   -k en-us

```

**Comment by kfirufk** [comment]
:( I just tried reinstalling again.. and this time the top panel got stuck again.. ctrl-f2 works of course. I guess it was a one-time luck, or that this problem happens randomly.
